# -*- coding: utf-8 -*-
"""lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BaSY6dZaNaOFlJJUxUZGr-UsXusZoLZm
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact, FloatSlider
from google.colab.patches import cv2_imshow


def gamma_correction_LUT(img, gamma, c=1.0):
    GAMMA_LUT = np.array([c*((i / 255.0) ** (1.0 / gamma)) * 255
                          for i in np.arange(0, 256)]).astype("uint8")


    return cv2.LUT(img, GAMMA_LUT)


def adjust_gamma(blue, green, red):
    im_gamma_b = gamma_correction_LUT(im_b, blue)
    im_gamma_g = gamma_correction_LUT(im_g, green)
    im_gamma_r = gamma_correction_LUT(im_r, red)


    im_gamma = cv2.merge([im_gamma_b, im_gamma_g, im_gamma_r])


    cv2_imshow(im_gamma)

filename = '/content/jato.jpg'
im = cv2.imread(filename)


im_b, im_g, im_r = cv2.split(im)

interact(
    adjust_gamma,
    blue=FloatSlider(value=1.0, min=0.1, max=3.0, step=0.1, description='Gamma Azul'),
    green=FloatSlider(value=1.0, min=0.1, max=3.0, step=0.1, description='Gamma Verde'),
    red=FloatSlider(value=1.0, min=0.1, max=3.0, step=0.1, description='Gamma Vermelho')
)

