# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WDW86HiD-TYnzqc56x1U6zB2ts0hyg5
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage import io, filters, color

def calculate_energy(image):
    # Convertendo a imagem para escala de cinza
    gray_image = color.rgb2gray(image)
    # Calculando o gradiente da imagem (energia baseada em bordas)
    energy = np.abs(filters.sobel_h(gray_image)) + np.abs(filters.sobel_v(gray_image))
    return energy

def find_seam(energy):
    r, c = energy.shape
    M = energy.copy()
    backtrack = np.zeros_like(M, dtype=int)

    for i in range(1, r):  # Iterar sobre as linhas
        for j in range(c):  # Iterar sobre as colunas
            if j == 0:
                idx = np.argmin(M[i-1, j:j+2])
                backtrack[i, j] = idx + j
                min_energy = M[i-1, idx + j]
            elif j == c - 1:
                idx = np.argmin(M[i-1, j-1:j+1])
                backtrack[i, j] = idx + j - 1
                min_energy = M[i-1, idx + j - 1]
            else:
                idx = np.argmin(M[i-1, j-1:j+2])
                backtrack[i, j] = idx + j - 1
                min_energy = M[i-1, idx + j - 1]

            M[i, j] += min_energy

    return M, backtrack

def remove_seam(image, backtrack):
    r, c, _ = image.shape
    output = np.zeros((r, c - 1, 3), dtype=image.dtype)
    j = np.argmin(backtrack[-1])

    for i in reversed(range(r)):
        output[i, :, 0] = np.delete(image[i, :, 0], [j])
        output[i, :, 1] = np.delete(image[i, :, 1], [j])
        output[i, :, 2] = np.delete(image[i, :, 2], [j])
        j = backtrack[i, j]

    return output

def seam_carving(image, num_seams_vertical=0, num_seams_horizontal=0):
    for _ in range(num_seams_vertical):
        energy = calculate_energy(image)
        M, backtrack = find_seam(energy)
        image = remove_seam(image, backtrack)  # Remove a seam da imagem

    image = np.transpose(image, (1, 0, 2))  # Transpor para remover seams horizontais
    for _ in range(num_seams_horizontal):
        energy = calculate_energy(image)
        M, backtrack = find_seam(energy)
        image = remove_seam(image, backtrack)  # Remove a seam da imagem
    image = np.transpose(image, (1, 0, 2))  # Voltar à orientação original

    return image

# Carregar a imagem
img = io.imread('/content/bolas.jpg')

# Aplicar o seam carving
new_image = seam_carving(img, num_seams_vertical=40, num_seams_horizontal=30)

# Mostrar a imagem original e a modificada
fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10, 5))
ax[0].imshow(img)
ax[0].set_title('Original Image')
ax[0].axis('off')

ax[1].imshow(new_image)
ax[1].set_title('Seam Carved Image')
ax[1].axis('off')

plt.tight_layout()
plt.show()

